//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdDay.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesInProject
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime EmployeeStart { get; set; }
        public Nullable<System.DateTime> EmployeeStop { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
