//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdDay.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.EmployeesInProject = new HashSet<EmployeesInProject>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> Stop { get; set; }
        public int CheifID { get; set; }
        public decimal Cost { get; set; }
        public int BonusAll { get; set; }
    
        public virtual Costumers Costumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesInProject> EmployeesInProject { get; set; }
    }
}
